version: "3.7"

services:
  app:
    build:
      args:
        user: ${username}
        uid: ${uid}
      context: ./
      dockerfile: ./php/Dockerfile
    container_name: asteroid-app
    restart: unless-stopped
    working_dir: /var/www/laravel_docker
    volumes:
      - ./laravel/:/var/www/laravel_docker
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - "9002:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY="base64:RTHljPVDNkxuRAz7m+GhAoHx5YNAeNPjCvg5Bhsvo1I="
      - DB_HOST=asteroid-db
      - DB_DATABASE="asteroids"
      - DB_USERNAME="root"
      - DB_PASSWORD="12345"

      - APP_TEST_KEY="base64:RTHljPVDNkxuRAz7m+GhAoHx5YNAeNPjCvg5Bhsvo1I="
      - DB_TEST_HOST=asteroid-test-db
      - DB_TEST_DATABASE="asteroids"
      - DB_TEST_USERNAME="root"
      - DB_TEST_PASSWORD="12345"
      - DB_TEST_DRIVER="mysql"
      - NASA_ASTEROIDS_API_KEY=${YOUR_NASA_ASTEROIDS_API_KEY}

    networks:
      - travellist
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: asteroid-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "asteroids"
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "12345"
    ports:
      - "3309:3306"
    volumes:
      - ./mysql/dbdata:/var/lib/mysql/
    networks:
      - travellist

  test_db:
    image: mysql:5.7
    container_name: asteroid-test-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "asteroids"
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "12345"
    ports:
      - "3308:3306"
    volumes:
      - ./mysql/test-dbdata:/var/lib/mysql/
    networks:
      - travellist



networks:
  travellist:
    driver: bridge
